[project]
name = "projet-git"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Antoine Collet", email = "antoine.collet0408@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dash>=4.4.1",
    "dash-bootstrap-components>=2.0.4",
]

[project.scripts]
projet-git = "projet_git:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
